### ISSUE TITLE
[1.19.2] Fix sync methods in UBlockEntity

### ISSUE THREAD

**Issue by HyCraftHD** [MC-U-Team/U-Team-Core#215]
Fix TODOs. They do not work in extreme cobble generator.

Stacktrace:

```java
java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.CompoundTag.getBoolean(String)" because "tag" is null
	at info.u_team.extreme_cobble_generator.blockentity.CobbleGeneratorBlockEntity.handleUpdateStateData(CobbleGeneratorBlockEntity.java:261) ~[%23188!/:?] {re:classloading}
	at info.u_team.u_team_core.blockentity.UBlockEntity.onDataPacket(UBlockEntity.java:101) ~[u_team_core-1.19.2-4.3.1.231_mapped_parchment_2022.09.04-1.19.2.jar%23190!/:4.3.1.231] {re:classloading}
```

https://github.com/MC-U-Team/U-Team-Core/blob/334929bde9a97e7c0c2a69e2acb03dffc8c26ffb/src/main/java/info/u_team/u_team_core/blockentity/UBlockEntity.java#L55

**Comment by HyCraftHD** [comment]
Fixed with this commit https://github.com/MC-U-Team/U-Team-Core/commit/fd398ce1554344cc2bc2b08f5a2533316992f9e5
