### ISSUE TITLE
[MC-Version] Bug short description

### ISSUE THREAD

**Issue by iambad1234** [MC-U-Team/U-Team-Core#58]
**Describe the bug**
My game is crashing whenever I have this mod in my mods folder,

**To Reproduce**
1. Download this mod 
2. Launch game

**Expected behavior**
My game wouldn't crash

**Screenshots**

**Versions**
- Minecraft version: 1.12.2
- Forge version: 14.23.5.2854
- UTeamCore version: 1.12.2-2.2.5.147-dev

**Log (if crash occures)**
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2/15/21 1:36 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from U Team Core (uteamcore)
Caused by: java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.getMinecraft()Lnet/minecraft/client/Minecraft;
	at info.u_team.u_team_core.intern.proxy.ClientProxy.postinit(ClientProxy.java:62)
	at info.u_team.u_team_core.UCoreMain.postinit(UCoreMain.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 418188024 bytes (398 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_G5 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID            | Version                 | Source                                   | Signature                                |
	|:----- |:------------- |:----------------------- |:---------------------------------------- |:---------------------------------------- |
	| LCHIJ | minecraft     | 1.12.2                  | minecraft.jar                            | None                                     |
	| LCHIJ | mcp           | 9.42                    | minecraft.jar                            | None                                     |
	| LCHIJ | FML           | 8.0.99.99               | forge-1.12.2-14.23.5.2854.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | forge         | 14.23.5.2854            | forge-1.12.2-14.23.5.2854.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | forgelin      | 1.8.4                   | Forgelin-1.8.4.jar                       | None                                     |
	| LCHIJ | betterfoliage | 2.2.0                   | BetterFoliage-MC1.12-2.2.0.jar           | None                                     |
	| LCHIJ | conquest      | 3.0.2                   | ConquestReforged-3.0.2-mc1.12.2.jar      | None                                     |
	| LCHIJ | blockpalette  | 1.5.0                   | ConquestReforged-3.0.2-mc1.12.2.jar      | None                                     |
	| LCHIJ | connect       | 1.0.3-mc1.12.2-SNAPSHOT | ConquestReforged-3.0.2-mc1.12.2.jar      | None                                     |
	| LCHIJ | orelib        | 3.6.0.1                 | OreLib-1.12.2-3.6.0.1.jar                | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJ | dsurround     | 3.6.1.0                 | DynamicSurroundings-1.12.2-3.6.1.0.jar   | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJ | ebwizardry    | 4.3.4                   | ElectroblobsWizardry-4.3.4-MC1.12.2.jar  | None                                     |
	| LCHIJ | llibrary      | 1.7.20                  | llibrary-1.7.20-1.12.2.jar               | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJ | iceandfire    | 1.9.1                   | iceandfire-1.9.1-1.12.2.jar              | None                                     |
	| LCHIJ | millenaire    | Millénaire 8.1.0        | millenaire-8.1.0.jar                     | None                                     |
	| LCHIE | uteamcore     | 2.2.5.147               | u_team_core-1.12.2-2.2.5.147-dev (1).jar | None                                     |
	| LCHI  | musicplayer   | 2.1.1.113               | music_player-1.12.2-2.1.1.113 (1).jar    | None                                     |
	| LCHI  | roguelike     | 1.8.0                   | RoguelikeDungeons-1.12.2-1.8.0 (1).jar   | None                                     |
	| LCHI  | waystones     | 4.0.72                  | Waystones_1.12.2-4.0.72.jar              | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  
ForgelinPlugin (Forgelin-1.8.4.jar)
  
BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 442.19' Renderer: 'GeForce GTX 960M/PCIe/SSE2'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 442.19
	OpenGlRenderer: GeForce GTX 960M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by HyCraftHD** [comment]
Please use the normal version and not the -dev version
